# Generated by Django 2.0.12 on 2019-10-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=100)),
                ('birthday', models.DateField()),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('rg', models.CharField(blank=True, default='', max_length=100)),
                ('cpf', models.CharField(blank=True, default='', max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=240)),
                ('observation', models.CharField(blank=True, max_length=240)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('X', 'Outro')], max_length=1)),
            ],
        ),
    ]
