# Generated by Django 2.0.12 on 2019-10-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people_control', '0003_auto_20191007_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='neoson',
        ),
        migrations.AddField(
            model_name='advisor',
            name='alumnus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people_control.Alumnus'),
        ),
    ]
