# Generated by Django 2.0.12 on 2019-10-10 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people_control', '0005_auto_20191009_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssumedNeoPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumed_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NeoPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='assumedneoposition',
            name='neo_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_control.NeoPosition'),
        ),
        migrations.AddField(
            model_name='assumedneoposition',
            name='neoson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_control.Neoson'),
        ),
    ]
