# Generated by Django 2.0.12 on 2019-10-10 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people_control', '0006_auto_20191009_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_request', models.DateTimeField()),
                ('date_requested', models.DateField()),
                ('comment', models.TextField(blank=True, default='')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_approver', to='people_control.Neoson')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_control.DayOfWeek')),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_work', models.BooleanField()),
                ('text', models.TextField(blank=True, default='')),
                ('operation', models.CharField(choices=[('+', 'NEO+'), ('-', 'NEO-'), ('', 'NEO'), ('', '')], max_length=100)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_control.DayOfWeek')),
                ('neoson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_control.Neoson')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_control.TimeSlot'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_control.RequestType'),
        ),
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_creator', to='people_control.Neoson'),
        ),
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_control.TimeSlot'),
        ),
    ]
