# Generated by Django 2.0.12 on 2019-10-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_control', '0002_auto_20191010_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='operation',
            field=models.CharField(choices=[('+10', 'NEO+'), ('-10', 'NEO-'), ('+0', 'NEO'), ('', '')], max_length=100),
        ),
    ]
